
class Niltukei_const:
    DATE_TIME64_NS = "datetime64[ns]"
    ZERO = 0
    HYPHEN = "-"
    HIZEKE_KOUMOKU = '日付'
    FILE_NAME_KABUKA = '_株価.csv'
    FILE_NAME_GYAKUHIBU = '_逆日歩_貸借桟.csv'
    FILE_NAME_SHINYOU = '_信用残.csv'
    FILE_NAME_MEARGE = '_マージ済み.csv'
    FILE_NAME_DIFFERENCE = '_差分.csv'
    FILE_NAME_RUISEKI = '_累積.csv'
    FILE_CSV_PATH = 'csv_path'
    DICT_WEB_DRIVER = 'WebDriverWait'
    DICT_DRIVER = 'driver'
    DICT_PANDAS = 'pd'
    DICT_COMMON_BY = 'By'
    DICT_CSV_PATH = 'csv_path'
    DICT_CSV_TITLE = 'title'
    WEB_DRIVER = '/home/user/anaconda3/envs/web_scraping/web_scraping/' \
        'web_scraping/'
    WEB_CHROME_DRIVER = 'chromedriver_116'
    CSV_PATH = "/home/user/anaconda3/envs/web_scraping/web_scraping/" \
        "web_scraping/Cumulative_stock_price_data/"
    UNNAMED_0_KOUMOKU = 'Unnamed: 0'
    RUISEKI_HAJIMARINE_KOUMOKU = '累積始値'
    RUISEKI_TAKENE_KOUMOKU = '累積高値'
    RUISEKI_YASUNE_KOUMOKU = '累積安値'
    RUISEKI_OWARINE_KOUMOKU = '累積終値'
    RUISEKI_URIKAIDAKA_KOUMOKU = '累積売買高'
    RUISEKI_SYUSEIGO_OWARINE_KOUMOKU = '累積修正後終値'
    RUISEKI_SHINYOU_URI_KOUMOKU = '累積信用売残'
    RUISEKI_SHINYOU_KAI_KOUMOKU = '累積信用買残'
    RUISEKI_SHINYOU_BAI_KOUMOKU = '累積信用倍率'
    RUISEKI_GYAKUHIBU_KOUMOKU = '累積逆日歩'
    RUISEKI_HIBU_KOUMOKU = '累積日歩日数'
    RUISEKI_KASHIKABU_ZAN = '累積貸株残'
    RUISEKI_YUSHI_ZAN_KOUMOKU = '累積融資残'
    MERGE_KOUMOKU = '_merge'
    HAJIMARINE_KOUMOKU = '始値'
    TAKENE_KOUMOKU = '高値'
    YASUNE_KOUMOKU = '安値'
    OWARINE_KOUMOKU = '終値'
    URIKAIDAKA_KOUMOKU = '売買高'
    SYUSEIGO_OWARINE_KOUMOKU = '修正後終値'
    SHINYOU_URI_KOUMOKU = '信用売残'
    SHINYOU_KAI_KOUMOKU = '信用買残'
    SHINYOU_BAI_KOUMOKU = '信用倍率'
    GYAKUHIBU_KOUMOKU = '逆日歩'
    HIBU_KOUMOKU = '日歩日数'
    JAPAN_SECURITIES_fINANCE = "日証金"
    KASHIKABU_ZAN = '貸株残'
    YUSHI_ZAN_KOUMOKU = '融資残'
    MERGE_KOUMOKU = '_merge'
    HTML_KABUKA_SEARCH = '株価'
    HTML_GYAKUBU_SEARCH = '逆日歩・貸借残'
    HTML_W668_SEARCH = "w668"
    HTML_OUTER_HTML_SEARCH = "outerHTML"
